### ISSUE TITLE
can not get the visualizations

### ISSUE THREAD

**Issue by mingbocui** [tim-fiola/network_traffic_modeler_py3#37]
```bash
>>> from graph_network import graph_network_interactive
>>> graph_network_interactive.make_interactive_network_graph(model1)
/Users/xxxx/.local/lib/python3.7/site-packages/mpld3/plugins.py:675: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(entry, collections.Iterable):
>>> Encountered exception.
main thread is not in main loop

This may be due to an mpld3 bug described in the link below:
https://github.com/mpld3/mpld3/issues/434

To overcome this bug, run the following command from the CLI to
get the mpld3 patch from github:
python3 -m pip install --user "git+https://github.com/javadba/mpld3@display_fix"
```

Hi, I run the demo and try to get the visualizations but got this error, seems to be the problem of mpld3 that something is deprecated, I run the suggested line `python3 -m pip install --user "git+https://github.com/javadba/mpld3@display_fix"` but did not repair this.

have you encountered this problem and how you solved it? Thanks a lot : )

**Comment by tim-fiola** [comment]
Hi Mingbo.  Thanks for bringing this to my attention.

The visualization using mpld3 (which is what you were using) is a beta
feature in the repo because of things like this; it's always been a bit
flaky.  I've run into weird things like this before, which is why I put
that message there.

Instead of troubleshooting something that I am going to remove from the
repo, I'd like to see if a *pending, improved beta visualization feature in
the dev branch can help you right now.

Can you try this:

   - Switch to the dev branch
   - go to the prototypes directory
   - put your model file in that directory
   - open up visualization_testing_2.py
      - on line 90 of that file, replace 'igp_shortcuts_model.csv' with the
      name of your model file
   - pip3 install the requirements in requirements_visualization.txt (in
   the newwork_traffic_modeler_py3 directory)
   - run visualization_testing_2.py
   - on your local browser, go to http://127.0.0.1:8050/
   - let me know what you see; you should see a very interactive network
   weathermap that allows you to select and visualize a lot of things such as
   demands, LSPs, interfaces, and visualize the paths


Thank you!
Tim

**Comment by tim-fiola** [comment]
Hi Mingbo.  I'm following up on this.  Have you tried my workaround detailed above?  Also, pyNTM 3.0 has just been released with an improved beta visualization feature.  

Info on this is posted in the wiki page: https://github.com/tim-fiola/network_traffic_modeler_py3/wiki/Visualizing-the-network-with-the-WeatherMap-Class-(beta)

I'll close this out in a few days if I've not heard back!

Thank you!
Tim

**Comment by tim-fiola** [comment]
closing this out as I have not heard back.  Please use https://github.com/tim-fiola/network_traffic_modeler_py3/wiki/Visualizing-the-network-with-the-WeatherMap-Class-(beta) to find out about the new WeatherMap feature, which provides improved capability and user experience
